openapi: 3.0.3
info:
  title: Decentralized ISO 20022 Microservice
  description: This is the API specificaiton for the APIs in the decentralized ISO 20022 microservice.
  version: 1.0.0
servers:
  - url: http://api.localhost.com/
    description: Endpoint example.
tags:
  - name: Internal
    description: For a financial institution to send a message to another financial institution.
  - name: External
    description: For a financial institution to receive a message from another financial institution.

paths:
  /api/v1/pacs:
    post:
      tags:
        - Internal
      summary: Send a pacs message to another financial institution.
      description: The endpoint where the financial insitution tells the microservice to send a pacs message to another financial institution.<br><br>A valid pacs message should be sent with a header head.001.001.02.
      requestBody:
        $ref: '#/components/requestBodies/Pacs.008.001.09Body'
      responses:
        '200':
          description: A pacs.002.001.12 message with the header head.001.001.02.
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string
        '400':
          description: An error message indicating that the message was invalid.
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string
        '403':
          description: An error message indicating that the sender or the receiver could not be authenticated.
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string
        '500':
          description: An error message indicating that an unknown error occurred.
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string
        '502':
          description: An error message indicating that the message could not be sent.
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string

  /api/v1/pacs:
    post:
      tags:
        - External
      summary: Receive a pacs message from another financial institution.
      description: The endpoint from which the microservice receives pacs messages from another financial institution.<br><br>A valid pacs message should be received with a header head.001.001.02.
      requestBody:
        $ref: '#/components/requestBodies/Pacs.008.001.09Body'
      responses:
        '200':
          description: A pacs.002.001.12 message with the header head.001.001.02.
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string
        '400':
          description: An error message indicating that the message was invalid.
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string
        '403':
          description: An error message indicating that the sender could not be authenticated. (The receiver is assumed to be authenticated)
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string
        '500':
          description: An error message indicating that an unknown error occurred.
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string
        '502':
          description: An error message indicating that the message could not be sent to the private financial institution handler.
          content:
            application/xml:
              schema: 
                type: array
                items: 
                  type: string
# WIP
components:
  schemas:
    RequestPayloadPacs.008.001.09:
      type: object
      xml:
        attribute: false
        wrapped: false
        name: RequestPayload
      properties:
        AppHdr:
          $ref: '#/components/schemas/AppHdr'
        Document:
          $ref: '#/components/schemas/Document'
    AppHdr:
      type: object
      properties:
        something:
          type: string
    Document:
      type: object
      properties:
        something:
          type: string
    RequestPayloadPacs.002.001.11:
      type: object
  requestBodies:
    Pacs.008.001.09Body:
      content:
        application/xml:
          schema:
           $ref: '#/components/schemas/RequestPayloadPacs.008.001.09'
    Pacs.002.001.11Body:
      content:
        application/xml:
          schema:
           $ref: '#/components/schemas/RequestPayloadPacs.008.001.09'
            